### ISSUE TITLE
Letter "o" in word "over" is transformed.

### ISSUE THREAD

**Issue by samliddicott** [blampe/goat#1]
Try:

echo "and over" | ./.local/go/bin/goat /dev/stdin > x.svg

the letter o alone is transformed into a large circle, the rest of the text is fine.

**Comment by dmullis** [comment]
Other cases of unwanted transformation from text to graphics:

```
v                 - isolated letter 'v'  
Alice v. CLS      - "Alice vs. CLS"  appears as expected, ordinary text
```

**Comment by dmullis** [comment]
Shows as fixed in https://github.com/blampe/goat/commit/4200b1fa948a2827319d9f5c0b6aaafa67f8b1cf
