### ISSUE TITLE
Edge cases don't render correctly

### ISSUE THREAD

**Issue by blampe** [blampe/goat#11]
Examples:
* [markdeep](https://casual-effects.com/markdeep/features.md.html#diagramexamples/digitalcircuits) | [goat](https://github.com/blampe/goat/blob/main/examples/circuits.svg)
* [markdeep](https://casual-effects.com/markdeep/features.md.html#diagramexamples/lineends) | [goat](https://github.com/blampe/goat/blob/main/examples/edge-cases.svg)

Markdeep's source became available after I hacked together this project many years ago. Its [`diagramToSVG`](9e512dc62bbd6d65750376068259596/1.13/markdeep.js#L3499) method is worth referencing.

**Comment by dmullis** [comment]
Firefox allows setting per-window background to a color different from the "theme" background.  Viewing this way the Markdeep example page cited above [lineends], note the white-filled circle at right (https://casual-effects.com/markdeep/features.md.html#diagramexamples/lineends)

![Screenshot 2022-05-16 at 19-53-35 Markdeep Feature Demo](https://user-images.githubusercontent.com/250338/168718913-54496bca-dbd5-437b-995c-ffe0d40ea8f2.png)

Conclusions:
1. Like Goat, Markdeep too fills opaquely the center of the seemingly "hollow" circle specified by 'o'.
2. Visually corrupt results are easily fallen into by code that attempts to guess the window background color.

**Comment by dmullis** [comment]
Edge case documented above was fixed.  Let's open individual bugs for whatever others remain.
