### ISSUE TITLE
Rendering in close corners  

### ISSUE THREAD

**Issue by katexochen** [blampe/goat#25]
Sometimes corners that are close to each other cannot be rendered as desired:

The following is kind of expected:
```
+----------+
|  PCRn    |
+----------+
+----------+
| Nonce    |
+----------+
```
![image](https://github.com/blampe/goat/assets/49727155/e4dba5eb-fd7e-42cc-a7e2-66ace3d27427)

It would be great if using other corners would not connect the two boxes: 

```
+----------+
|  PCRn    |
'----------'
.----------.
| Nonce    |
+----------+
```
but it currently renders the same as with `+`

**Comment by dmullis** [comment]
See fix referenced above.

**Comment by dmullis** [comment]
Fix mentioned above will be preserved in https://github.com/dmullis/goat/tree/github-test, rather than the main branch of my fork.

**Comment by dmullis** [comment]
Fixed in 
https://github.com/blampe/goat/pull/35/commits/a4c2da8def73c96d0d4de69adfa361f7ce87a158
