### ISSUE TITLE
Not sure I like what goat makes out of matchstick people

### ISSUE THREAD

**Issue by cabo** [blampe/goat#4]
```
  O    +-------+
 -|--->| hi!   |
 / \   +-------+
```

I'd like this to be a bit more gender-neutral.

**Comment by dmullis** [comment]
Perhaps best taken as a joke.  However, a little experimentation show passable matchstick people can be drawn.
<pre>
         * 
  *     -+-
 -+-     + 
 / \    / \
</pre>

**Comment by blampe** [comment]
Closing in favor of a the more constructive #11.
