### ISSUE TITLE
Diagrams as text - Sequence diagram, network diagram - Feature request

### ISSUE THREAD

**Issue by terokarvinen** [blampe/goat#6]
Could goAT support writing diagrams as code?

For example, a sequence diagram [1, 3] could be 

```
Alice -> Bob: Hello Bob!
Alice <- Bob: Hello Alice!
```

Also, drawing computer network diagrams is a very common task. It's even included in goAT examples [2, 4]. 

Describing these diagrams as text would be much easier and more robust than drawing them one ASCII byte at a time. With Hugo, this would mean just writing my diagrams, saving, and seeing them render in front of my eyes automatically when running 'hugo serve'. 

ps. Thanks for goAT!  

[1] https://arthursonzogni.com/Diagon/#Sequence

[2] https://github.com/bep/goat/blob/master/examples/icons.svg

[3] ![sequence-diagram-text-diagon](https://user-images.githubusercontent.com/642663/158172155-5e193777-d485-4536-bb94-3c093b320be8.png)

[4] ![goat-examples-icons-svg](https://user-images.githubusercontent.com/642663/158172260-955489c4-731f-4046-86a4-d1cab51d3921.png)
g

**Comment by blampe** [comment]
I love the idea, but it's definitely outside the scope of this project. The more complicated examples were borrowed from [markdeep](http://casual-effects.com/markdeep/), and they're much more about "what's possible" than "what's reasonable" to do with the tool.

There are certainly other, better tools for generating plaintext diagrams -- https://xosh.org/text-to-diagram/ has a pretty exhaustive list you might find helpful!

**Comment by dmullis** [comment]
FYI, GitHub endorses _Mermaid_ for this purpose.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
